# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-19 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_auto_20170417_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleusercontact',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
