# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-27 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0004_auto_20170419_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitterprofile',
            name='oauth_secret',
        ),
        migrations.RemoveField(
            model_name='twitterprofile',
            name='oauth_token',
        ),
        migrations.AddField(
            model_name='twitterprofile',
            name='twitter_user_id',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
