# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-03 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0006_twitterusercontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleuser',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
