# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 12:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
