# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 06:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20170221_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_experience',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
