# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20170222_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
