# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20170222_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='applicant_gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_experience',
            field=models.IntegerField(),
        ),
    ]
