# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_remove_applicant_joining_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_description',
            field=models.CharField(max_length=255),
        ),
    ]
