# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 10:23
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_auto_20170223_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_description',
            field=ckeditor.fields.RichTextField(max_length=1255),
        ),
    ]
