# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_auto_20170223_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='currently_working_with',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='experience',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='graduation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='graduation_percentage',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='post_graduation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='post_graduation_percentage',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='tenth_percentage',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='twelth_percentage',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
    ]
