# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_auto_20170227_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='current_position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
