# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_auto_20170301_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='skills',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_location',
            field=models.CharField(choices=[('delhi', 'DELHI'), ('noida', 'NOIDA'), ('gurgaon', 'GURGAON'), ('banglore', 'BANGLORE'), ('pune', 'PUNE')], max_length=20),
        ),
    ]
