# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-02 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_auto_20170301_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='applicant_pic',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/'),
        ),
    ]
