# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-02 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_applicant_applicant_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='applicant_pic',
            field=models.ImageField(default='images/None/no-img.jpg', upload_to='images/'),
        ),
    ]
