# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-03 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0019_auto_20170302_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_user',
            field=models.BooleanField(default=False),
        ),
    ]
