# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-03 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0021_auto_20170303_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.CharField(blank=True, max_length=500, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('job_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='job.Job')),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='usersmessage',
            name='job',
        ),
        migrations.RemoveField(
            model_name='usersmessage',
            name='name',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='applicant_pic',
            field=models.ImageField(default='media/None/no-img.jpg', upload_to='media/'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='UsersMessage',
        ),
    ]
