# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-04 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0022_auto_20170303_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='email',
        ),
        migrations.AddField(
            model_name='applicationtime',
            name='applicant_status',
            field=models.CharField(blank=True, choices=[('Applied', 'Applied'), ('Call for Telephonic round', 'Call for Telephonic round'), ('Call for Technical round', 'Call for Technical round'), ('Call for HR round', 'Call for HR round')], default='Applied', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='docs/'),
        ),
        migrations.AlterField(
            model_name='applicationtime',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.Applicant'),
        ),
    ]
