# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-04 12:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0024_auto_20170304_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='username',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
