# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-04 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0025_messages_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='username',
        ),
    ]
