# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-09 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0026_remove_messages_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='applicant_pic',
            new_name='employee_pic',
        ),
        migrations.AlterField(
            model_name='applicationtime',
            name='applicant_status',
            field=models.CharField(choices=[('1', 'Applied'), ('2', 'Called for Telephonic round'), ('3', 'Called for Technical round'), ('4', 'Called for HR round'), ('5', 'Selected')], default='1', max_length=255),
        ),
        migrations.AlterField(
            model_name='messages',
            name='body',
            field=models.CharField(max_length=500),
        ),
    ]
