# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-09 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0029_auto_20170309_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_pic',
            field=models.ImageField(default='media/None/no-img.jpg', upload_to='media/'),
        ),
    ]
