# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-14 10:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0030_auto_20170309_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='applicant_pic',
            field=models.ImageField(default='/None/no-img.jpg', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='applicationtime',
            name='applicant_status',
            field=models.CharField(choices=[('1', 'Applied'), ('2', 'Called for Telephonic round'), ('3', 'Called for Technical round'), ('4', 'Called for HR round'), ('5', 'Selected'), ('6', 'Declined')], default='1', max_length=255),
        ),
    ]
