# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-17 11:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0034_auto_20170317_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
