# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-22 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0036_auto_20170321_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailedContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephonic_call_content', models.CharField(max_length=1000)),
                ('technical_round_call_content', models.CharField(max_length=1000)),
                ('hr_round_call_content', models.CharField(max_length=1000)),
                ('selection_call_content', models.CharField(max_length=1000)),
                ('jobpost_mail_content', models.CharField(max_length=1000)),
                ('application_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.ApplicationTime')),
            ],
        ),
    ]
