# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-22 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0037_mailedcontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailedcontent',
            name='hr_round_call_content',
        ),
        migrations.RemoveField(
            model_name='mailedcontent',
            name='jobpost_mail_content',
        ),
        migrations.RemoveField(
            model_name='mailedcontent',
            name='selection_call_content',
        ),
        migrations.RemoveField(
            model_name='mailedcontent',
            name='technical_round_call_content',
        ),
        migrations.RemoveField(
            model_name='mailedcontent',
            name='telephonic_call_content',
        ),
        migrations.AddField(
            model_name='mailedcontent',
            name='mailed_content',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='mailedcontent',
            name='status_mailed_for',
            field=models.CharField(choices=[('1', 'Applied'), ('2', 'Called for Telephonic round'), ('3', 'Called for Technical round'), ('4', 'Called for HR round'), ('5', 'Selected'), ('6', 'Declined')], default='1', max_length=255),
        ),
    ]
